server:
  port: 8081


#person:
#  lastName: zhangsan  # 写成 last-name也可以识别
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1, k2: 12}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 2



